version: '3.5'
  
services:
    crawler:
        build:
          context: ./

        volumes:
          - ./crawls:/crawls

        cap_add:
          - NET_ADMIN
          - SYS_ADMIN

        shm_size: 1gb

